### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by svenluijten** [decahedronio/laravel-5-unofficial-docs#2]
I'd love to help contribute to some Dutch translations if need be. I know quite a few of my classmates would definitely benefit from that, and I'm fairly sure some other people who don't speak English from around the world would find it beneficial as well.

Thoughts?

**Comment by Harry-Torry** [comment]
(nothing constructive to add)

Sounds like a good idea as long as we keep everything inline.

**Comment by Helfull** [comment]
well, so i can help with the german translation

**Comment by jpmurray** [comment]
I'd add French to the lot.

**Comment by thomasruiz** [comment]
I'll help with french. But don't we need something before thinking about translations? :yum:
